### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by thangngoc89** [jslauthor/react-audio-component#1]
Hi there,

This is an awesome project for a real react audio player :+1: . But as I can see, it doesn't support mobile devices yet. I built a howler's wrapper component to play audio with React. You can check it out, most of APIs are similar with your ReactAudio component 

Project's link: https://github.com/thangngoc89/react-howler

**Comment by jslauthor** [comment]
Thanks and that's awesome! I had looked into howler for another project--seems like a great interface. 

The audio player almost works in mobile. It needs a few tweaks.

**Comment by jslauthor** [comment]
Nice work on the wrapper btw.

**Comment by jslauthor** [comment]
Okie dokie, I added basic mobile features. Can swipe the album to change songs and it removes the volume slider. Works down to iPhone 5 resolutions. Not perfect, but hey, not bad. :)

**Comment by thangngoc89** [comment]
Great to hear it
